server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shopping
    password: root
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
